# sweep_config.yaml
# Defines the hyperparameter search space for the MAML-TRPO algorithm.
# This file will be loaded by our Python script to create the sweep.

name: MAML_TRPO_HALFCHEETAHFORWARDBACKWARD_SWEEP
method: bayes
metric:
  name: adaptation_reward
  goal: maximize
parameters:
  adapt_lr:
    distribution: log_uniform_values
    min: 0.01
    max: 0.1
  meta_lr:
    distribution: log_uniform_values
    min: 0.8
    max: 1.2
  adapt_steps:
    values: [1, 2, 3]
  gamma:
    value: 0.9
  tau:
    value: 0.95
  adapt_bsz:
    values: [20, 30]
  meta_bsz:
    values: [20, 30]
